const Map<String, dynamic> enLocalizedValues = {
  'app_title': 'Local Pixiv',
  'tab_title': {
    'h': 'Home',
    'v': 'Viewer',
    'f': 'Following',
    's': 'Settings',
  },
  'home_page': {
    'ef': '( ･ω･)☞   (:3 」∠)',
    'ew': 'Enter work Id',
    'eu': 'Enter user Id',
    'ek': 'Enter keywords',
    'er': '٩( ᐛ )و',
    'connect_error': 'ConnectError:\nProxy inaccessible',
    'proxy_error': 'Please checking proxy settings.',
    'start': 'Start',
    'stop': 'Stop',
    'clear': 'Clear',
    'cf': 'Followings',
    'ci': 'Id',
    'cu': 'User',
    'ct': 'Tags',
    'cr': 'Ranking',
  },
  'viewer_page': {
    'search': 'Search',
    'advanced_search': 'Advanced Search',
    'loading': 'Loading......',
  },
  'user_detial_page': {'no_more_data': 'No More Data'},
  'settings_page': {
    'basic': 'Basic Settings',
    'theme': 'Theme Settings',
    'search': 'Search Settings',
    'performance': 'Performance Settings',
    'webCrawler': 'WebCrawler Settings',
    'other': 'Other Settings',
    'about': 'About',
  },
  'basic_page': {
    'title': 'Basic Settings',
    'host_path': 'Host Path',
    'font_size': 'FontSize (This is an example.)',
    'use_mongo_db': 'Use MongoDB',
    'server_host': 'Server Host'
  },
  'theme_page': {
    'title': 'Theme Settings',
    'system': 'System Theme',
    'light': 'Light Theme',
    'dark': 'Dark Theme',
    'click_choose_color': 'Click to select a color you want to change',
    'select_color': 'Select color',
    'select_color_shade': 'Select color shade',
    'selected': 'Selected color and its shades',
  },
  'search_page': {
    'title': 'Search Settings',
    'auto_open': 'Auto open user detial page when click user infos',
    'auto_search': 'Auto search when click tag',
  },
  'performance_page': {
    'title': 'Performance Settings',
    'image_cache_rate': 'ImageCacheRate',
    'not_limited': 'Not limited',
  },
  'webCrawler_page': {
    'title': 'WebCrawler Settings',
    'cookies': 'Cookies',
    'enable_proxy': 'Enable Proxy',
    'http_proxy': 'Http Proxy',
    'https_proxy': 'Https Proxy',
    'enable_resverse_proxy': 'Enable Resverse Proxy',
    'resverse_proxy_example': 'Resverse Proxy (eg i.pximg.net)',
    'download_style': 'Download Style',
    'illust': 'Illust',
    'manga': 'Manga',
    'novel': 'Novel',
    'ugoira': 'Ugoira',
    'series': 'Series',
    'concurrency': 'Concurrency',
    'larger_than_one': 'Concurrency must large than 1',
    'client_pool': 'ClientPool',
    'add': 'Add',
  },
  'other_page': {
    'title': 'Other Settings',
  },
  'about_page': {
    'title': 'About',
    'about': 'About......',
  },
  'loader': {
    'invalid':
        'Invalid image data! The image file may be corrupted. It will be deleted automatically.',
    'error': 'Error loading image',
  },
  'bookmark_tool_tip': {
    'y': 'Cancel Bookmark',
    'n': 'Bookmark',
  },
  'page_controller': {
    'prev': 'Prev',
    'jump': 'Jump',
    'next': 'Next',
    'input': 'Page',
  },
  'not_following_warn': 'NOT FOLLOWING NOW!',
  'actions': {
    'yes': 'Yes',
    'no': 'No',
    'apply': 'Apply',
    'cancel': 'Cancel',
  },
  'account': {
    'name_or_email': 'Account Name or E-mail',
    'cookie': 'Account Cookie',
    'info': 'Account Info',
  },
  'open_link': 'Open Link ?',
};
