const Map<String, dynamic> zhlocalizedValues = {
  'database_operation': {
    'search': '搜索',
    'update': '更新',
  },
  'app_title': '本地Pixiv',
  'tab_title': {
    'h': '首页',
    'v': '查看器',
    'f': '关注',
    's': '设置',
  },
  'home_page': {
    'ef': '( ･ω･)☞   (:3 」∠)',
    'ew': '输入作品ID',
    'eu': '输入用户ID',
    'ek': '输入关键词',
    'er': '٩( ᐛ )و',
    'connect_error': '连接错误：\n代理不可访问',
    'proxy_error': '请检查代理设置。',
    'start': '开始',
    'stop': '停止',
    'clear': '清除',
    'cf': '关注',
    'ci': 'ID',
    'cu': '用户',
    'ct': '标签',
    'cr': '排名',
  },
  'viewer_page': {
    'search': '搜索',
    'advanced_search': '高级搜索',
    'loading': '加载中......',
    'text_fommat_incorrect': '搜索文本格式不正确。',
    'result_found': '找到结果。',
    'no_result_found': '未找到匹配结果！',
  },
  'user_detial_page': {'no_more_data': '没有更多数据'},
  'tag_page': {
    'search': '搜索',
    'like': '喜欢标签',
    'dislike': '不喜欢标签',
    'add_tag': '添加标签',
    'tag_exist': '标签已存在。',
    'tag_not_find': '未找到标签。',
    'tag_add_to_other': '标签已添加到',
    'update': '更新',
  },
  'settings_page': {
    'basic': '基本设置',
    'theme': '主题设置',
    'search': '搜索设置',
    'performance': '性能设置',
    'webCrawler': '网页爬虫设置',
    'other': '其他设置',
    'about': '关于',
  },
  'basic_page': {
    'title': '基本设置',
    'host_path': '主机路径',
    'font_size': '字体大小 (示例)',
    'use_mongo_db': '使用MongoDB',
    'server_host': '服务器主机'
  },
  'theme_page': {
    'title': '主题设置',
    'system': '系统主题',
    'light': '浅色主题',
    'dark': '深色主题',
    'click_choose_color': '点击选择要更改的颜色',
    'select_color': '选择颜色',
    'select_color_shade': '选择颜色阴影',
    'selected': '已选颜色及其阴影',
  },
  'search_page': {
    'title': '搜索设置',
    'auto_open': '点击用户信息时自动打开用户详情页',
    'auto_search': '点击标签时自动搜索',
  },
  'performance_page': {
    'title': '性能设置',
    'image_cache_rate': '图片缓存率',
    'not_limited': '不限制',
  },
  'webCrawler_page': {
    'title': '网页爬虫设置',
    'cookies': 'Cookie',
    'enable_proxy': '启用代理',
    'http_proxy': 'HTTP代理',
    'https_proxy': 'HTTPS代理',
    'enable_resverse_proxy': '启用反向代理',
    'resverse_proxy_example': '反向代理 (例如 https://i.pximg.net)',
    'download_style': '下载类型',
    'illust': '插画',
    'manga': '漫画',
    'novel': '小说',
    'ugoira': '动图',
    'series': '系列',
    'concurrency': '并发数',
    'larger_than_one': '并发数��须大于1',
    'client_pool': '客户端池',
    'add': '添加',
  },
  'other_page': {
    'title': '其他设置',
  },
  'about_page': {
    'title': '关于',
    'about': '关于......',
  },
  'loader': {
    'invalid': '无效的图像数据！图像文件可能已损坏。它将被自动删除。',
    'error': '加载图像错误',
  },
  'bookmark_tool_tip': {
    'y': '取消收藏',
    'n': '收藏',
  },
  'page_controller': {
    'prev': '上一页',
    'jump': '跳转',
    'next': '下一页',
    'input': '页码',
  },
  'not_following_warn': '未关注！',
  'actions': {
    'yes': '是',
    'no': '否',
    'apply': '应用',
    'cancel': '取消',
    'success': '成功',
    'fail': '失败',
  },
  'account': {
    'name_or_email': '账户名称或邮箱',
    'cookie': '账户Cookie',
    'info': '账户信息',
  },
  'open_link': '打开链接？',
};
